# docker-compose.yml
version: '3'

services:

 jupyterliteapp:
    build: .
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    #labels:
    #  traefik.enable: true
    #  traefik.docker.network: traefik_web
    #  traefik.http.routers.flaskapp.entrypoints: websecure
    #  traefik.http.routers.flaskapp.rule: 'Host(`jupyterlite.alkemata.com`)'
    #  traefik.http.services.flaskapp.loadbalancer.server.port: 8000
    networks:
      - jup_default

networks:
  jup_default:
    driver: bridge