# docker-compose.yml
version: '3'

services:

 jupyterliteapp:
    build: .
    volumes:
      - ./:/app/
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_web
      traefik.http.routers.jupyterliteapp.entrypoints: websecure
      traefik.http.routers.jupyterliteapp.rule: 'Host(`jupyterlite.alkemata.com`)'
      traefik.http.services.jupyterliteapp.loadbalancer.server.port: 8000
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
